name: 'DOCTOC Action'
description: 'Apply DOCTOC to whole filetree'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

#   Removing this since it's not clear if it's even doing anything or helping
#   Certainly it makes not meaningful improvement.
#        - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/${{github.action_path}}.npm
#          key: npm-${{ hashFiles('package-lock.json') }}
#          restore-keys: npm-

      - name: Install dependencies
        shell: bash
        run: |
           cd ${{github.action_path}}
           npm ci

      - name: Run DODCTOC
        shell: bash
        run: |
           cd ${{github.workspace}}
           ${{github.action_path}}/node_modules/.bin/doctoc .
           
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
